name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important! Ensures full git history

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: usmaniqbal2410
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/github-contribution-grid-snake.svg"
          message: "Update contribution snake"
          push: true
          pull: "--rebase"
